// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9zHYvh0r5WDqsHYf89YZvXX7ogoNpf9I',
    appId: '1:1068394866758:web:bc39496ebb9700c3528247',
    messagingSenderId: '1068394866758',
    projectId: 'my-project-59b59',
    authDomain: 'my-project-59b59.firebaseapp.com',
    storageBucket: 'my-project-59b59.firebasestorage.app',
    measurementId: 'G-YE4TPMGWGH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDunhKsxPpZ7TjB6JMM-ovx_wbmxH4q4k0',
    appId: '1:1068394866758:android:aef3d93d380dc6a3528247',
    messagingSenderId: '1068394866758',
    projectId: 'my-project-59b59',
    storageBucket: 'my-project-59b59.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBqKxt3x2a62lrYMCeY-h4OrN_qQPpMV0',
    appId: '1:1068394866758:ios:f2de38ca0306b1c1528247',
    messagingSenderId: '1068394866758',
    projectId: 'my-project-59b59',
    storageBucket: 'my-project-59b59.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBqKxt3x2a62lrYMCeY-h4OrN_qQPpMV0',
    appId: '1:1068394866758:ios:f2de38ca0306b1c1528247',
    messagingSenderId: '1068394866758',
    projectId: 'my-project-59b59',
    storageBucket: 'my-project-59b59.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9zHYvh0r5WDqsHYf89YZvXX7ogoNpf9I',
    appId: '1:1068394866758:web:c615ffceb9357f8e528247',
    messagingSenderId: '1068394866758',
    projectId: 'my-project-59b59',
    authDomain: 'my-project-59b59.firebaseapp.com',
    storageBucket: 'my-project-59b59.firebasestorage.app',
    measurementId: 'G-NBC48W4WD5',
  );
}
